### ISSUE TITLE
Debug code (LINE CHECK) left in public release

### ISSUE THREAD

**Issue by itzLukeYo** [SchitzPseudonym/VariantFurnaces#1]
Hi! It seems you've left some of your debug code in the public release version.

**To Reproduce**
1. Run fabric server with mod installed
2. Open any variant furnace
3. Check server console
4. "LINE CHECK 3" appears every time

**Expected behavior**
No "LINE CHECK 3" console spam plz

**Comment by BananaPuppy** [comment]
I will push a fix for this in a week max, thanks for letting me know this issue exists.
